sudo: required

language: node_js

node_js:
  - node

cache: yarn

services:
  - docker

env:
  global:
    # HEROKU_API_KEY
    - secure: "Pa0Gs5nfewMaJxYtAMGqoasZ2im/GrxQjsHm2/sPE2lKQPdE87BwG9HHbSUAzv/PF5KHJU59HLl/58+vctB20Y2SnaKUX0MiEsgGNFG2dOEA2naJsze00qbnT8my0SA042y1/k77whpRJQhd3Fqu/e7OIjO+04C97/CqxQSng67pOZKVIBJabF0u0zleZTSQ+kX6c5s9YMbAEB9uIPXAEsrU36onAdTlRBHmZ6kCx/BLncyl63Ywvg4GGhPTgqq3hOM2sHEXMkNxR07qTsrGC/sbvMSUgr/O9MCYcWRxoUaov3Ojoi8+sd1KbkdHWT+lmjtELTGrHOf/8zlxRy8ec17JEibrbskkXcznjbwXpXTFBOrLsZWpAeVE6zrb1Q5SR5FVsVPgw4/UeBml1/yr7U4o8MiF2RPXf55LM+MM8sKlicHteQCDDikgef0NAKXPKUQEzW9D6ZppRGZUrzDBmDh4b1cSavqCzSJYjewZzG6MmFX4fC1jtH3QeBiARcO7xooldF9IPhz0yya9KgUU45qpdbqQhJzhLFrGScKTztZPGi2wgCnnkeO7AuG4LI4joe2D2KQbXajPEcGORP4jAUB+3oqNGVGgsiVklMtYfz4S1uDolVRYwCDzQCRf/3gi3AK3iuc9WgvHculchrZdZ8sv6Cy99q3ouIWPm6tVYHw="
    # DOCKER_USERNAME
    - secure: "fP9Y6ZtAbtAlV0iGzAUSeWuYFn2WN4DrCYWajghYtFh9sKhhSTkuFc8Wgv8Ies4+LhGy8Bu7Fk/yaOYIRl1zyey3WwuhOAXyRGU4fBm/HXBtxhPxtPGzOMIplFj2U/TnHZpt+uKpoo7duGIptCyDaGyrCsb4uM7/CK1UbXyuaDTj2yVzYKmvldjpSrFjNvi+05msHZcSPMDI2QJqoQkS/ou+UJd1Te+TS1CBiO8+bZ2tbsTxs19OS0g6CjoFaLcL11VW/31Uf+YLU5LNnfSUjhxSeu1xivNwcavh7f0rZYw9rW6VE+PoZx8aTcBmKhRwFJbEAPoT4zsudrRpDY5uzmDP9H03NXQl7XEmHJb5or86wiYRPSfnAkzvx97IEtcd0uPkmczH8KgcsNdtGsdHKwD57BLURC1F1gXqe4QzFhnrZEOhzjNq2bhWl7q0ClDcSuTz3jSXw/inm/B1Vl0EbeTohWWbmeWXNPlp7dmHDr7dNiqIgZn6eZoI0i0qZoQCqmRBORsVWQv7i24jBhUwJG6/Y5MjM4FkwzEy1mOd3E2ZxpZHhZlImv2TDPDIfHtdbvm9tQjzgQC7H5wrRd07AYimRPQu9JH3Ehk4GA/NUhfrF3UdapwVHWffBI5PpvwXxlGrQpu57zqSP8XD1jYR+3bNAx4/Jf2Av9V2F0WnqFc="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

before_script:
  - yarn run generate-graphql-schema

script:
  - yarn run lint
  - yarn run test
  - yarn run build

after_success:
  - .travis/after_success.sh

branches:
  only:
  - master
